notifications:
  email: false
language: python
python:
  - "3.6"
env:
  - TOX_ENV=py36
  - TOX_ENV=coveralls
  - TOX_ENV=flake8
install: pip install tox
script: tox -e $TOX_ENV
jobs:
  include:
    - name: Build dist
      before_install: pip install awscli pipenv
      install: pipenv install
      script: make dist
    - stage: deploy
      before_install:
        - pip install pipenv awscli
        - make deps
        - pipenv clean
        - pip install pipenv
      install: pipenv sync
      script: skip
      deploy:
        provider: script
        script: make stage
