notifications:
  email: false
language: python
python:
  - "3.6"
env:
  - TOX_ENV=py36
  - TOX_ENV=coveralls
  - TOX_ENV=flake8
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
before_deploy: pip install awscli
deploy:
  skip_cleanup: true
  provider: script
  script: make stage
